name: GitHub-Profile-3D-Contrib-Dynamic-Theme

on:
  schedule:
    - cron: "0 3 * * *" # 03:00 JST (18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: manage-dynamic-theme
    steps:
      - uses: actions/checkout@v4
      - name: Copy SVG Files for Dynamic Theme
        run: |
          cp profile-3d-contrib/profile-green.svg profile-3d-contrib/light-theme.svg
          cp profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/dark-theme.svg
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "updated light and dark theme SVGs" || echo "No changes to commit"
          git push
