name: GitHub-Profile-3D-Contrib-Dynamic-Theme

on:
  schedule:
    - cron: "0 3 * * *" # 03:00 JST (18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: manage-dynamic-theme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/yousuf0076/github-profile-3d-contrib.git
          # در صورت استفاده از ابزار دیگر، اینجا تغییر دهید

      - name: Create profile-3d-contrib directory
        run: |
          mkdir -p profile-3d-contrib

      - name: Generate SVG files
        run: |
          github-profile-3d-contrib --username <your-username> --output-dir profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy SVG Files for Dynamic Theme
        run: |
          cp profile-3d-contrib/profile-green.svg profile-3d-contrib/light-theme.svg || echo "Failed to copy light-theme.svg"
          cp profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/dark-theme.svg || echo "Failed to copy dark-theme.svg"
        continue-on-error: true

      - name: Debug directory structure
        run: |
          ls -la profile-3d-contrib/

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/*.svg
          git commit -m "Updated light and dark theme SVGs" || echo "No changes to commit"
          git push
