name: GitHub-Profile-3D-Contrib-Dynamic-Theme

on:
  schedule:
    - cron: "0 3 * * *" # 03:00 JST (18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: manage-dynamic-theme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create profile-3d-contrib directory
        run: |
          mkdir -p profile-3d-contrib

      - name: Generate 3D Contribution SVGs
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: "sample-settings/rainbow.json" # اختیاری، برای تم‌های خاص

      - name: Copy SVG Files for Dynamic Theme
        run: |
          cp profile-3d-contrib/profile-green.svg profile-3d-contrib/light-theme.svg || echo "Failed to copy light-theme.svg"
          cp profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/dark-theme.svg || echo "Failed to copy dark-theme.svg"
        continue-on-error: true

      - name: Debug directory structure
        run: |
          ls -la profile-3d-contrib/

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/*.svg
          git commit -m "Updated light and dark theme SVGs" || echo "No changes to commit"
          git push
